### ISSUE TITLE
第一次可以正常缩放框，但是第二次框会变为初始大小

### ISSUE THREAD

**Issue by followingjoneses** [fdu14ss/app#2]
框的高和宽是有对象box.wide和box.height来控制的，每次drag都会改变box.wide和box.height，并且我在console中打印出来box.wide和box.height的值确实变了，但是当第二次触发drag事件是，box.wide和box.height又变为初始值了。不知道什么情况，可能是和$timeout的回调函数有关？

**Comment by jt-wang** [comment]
@jzlshitian 把 solution 在这边写一下~ 方便《软件实践》课用

**Comment by followingjoneses** [comment]
已解决，解决办法是讲触发事件从on-tap变为on-touch，并且最好不要用style.transform去改变dom对象的位置以及大小，直接用style.left和style.top改变位置，用style.width和style.height改变大小。
