### ISSUE TITLE
关于如何时时改变view中热点框的大小

### ISSUE THREAD

**Issue by followingjoneses** [fdu14ss/app#6]
angular中不是采用数据双向绑定吗？我view中框的长和宽是由model中数据来操控的。为什么我改了model中的值，view中框的大小却没有改变呢？

**Comment by followingjoneses** [comment]
尝试运用view中的event.style.transform，但子元素的四个框的位置会产生奇怪的偏移。

**Comment by followingjoneses** [comment]
已解决，通过修改拖拽元素及其领节点的style.top,style.left属性，还有修改父元素热点框的top,left,width,height属性，可以成功实现时时缩放，并且通过修改model中的box对象可以做到保存这种修改。

**Comment by N4A** [comment]
学习了
